cc_library(
    name="matrix",
    srcs=[
        "matrix.cpp",
    ],
    hdrs = [
        "matrix.hpp",
    ],
    linkopts = [
        "-lpthread",
    ],
    visibility = ["//visibility:public"],
)
