cc_library(
    name="Lattice",
    srcs=[
        "Lattice.cpp"
    ],
    hdrs = [
        "Lattice.hpp",
    ],
    deps = [
        "//Server/main/Lattice/matrix:matrix",
        "//Server/main/Lattice/PublicEncryption:PublicEncryption",
    ],
    visibility = ["//visibility:public"],
)
