cc_library(
    name = "main",
    srcs = [
        "main.cpp",
    ],
    hdrs = [
        "main.hpp",
    ],
    deps = [
        "//Server/main/Lattice:Lattice",
    ],
    visibility = ["//visibility:public"],
)